K: 3
N: 7
maxHops: 11
outputDir: ./output
staticNodes:
  0:
    role: "buyer"
    buyeroptionlist:
      - "boars"
  1:
    role: "buyer"
    items:
      - "boars"
  2:
    role: "buyer"
    buyeroptionlist:
      - "boars"
excludeEdges:
  - [1,2]
includeEdges:
  - [0,1]
# Example of a host list for the nodes to be run on
hosts:
  - "localhost"
